### PR TITLE
Adds `args` string_list option to proto_compile

### LINKED ISSUE #57: make proto_compile accept additional args?
I think it would be nice to allow users to provide custom arguments to protoc. Currently, there doesn't seem to be a way to do it.

My current use case, I'm trying to generate _only_ a proto descriptor set using the following:

```
proto_compile(
  name = "person_proto",
  protos = ["person.proto"],
  langs = [],
  args = [
    "--include_imports",
    "--include_source_info",
  ],
)
```
With the hope that this would result in the following command:
`protoc --include_imports --include_source_info person.proto --descriptor_set_out person.descriptor_set`

However, I can't figure out a way to make the `args` attr available to protoc. What do you think about this idea?

### PR DESCRIPTION
**Pull request by pcj**
* Also makes the `langs` attribute non-mandatory.

Closes #57

### CODE REVIEW

**Comment by pcj** [comment]
@perezd Does this LGTY?

**Comment by perezd** [comment]
Interesting second observation, using this approach, I don't believe I can have proto A depend on proto B and have them both appear in a descriptor_set. Can I specify proto_deps in proto_compile in some way?

**Comment by perezd** [comment]
Another thing I'm noticing, there is no way to reference well known protos via only proto_compile, is there? That is a filegroup of protos listed at `@com_github_google_protobuf//:well_known_protos`...Is there a way to get these in the right place?

**Comment by pcj** [comment]
I updated the example for `well_known_protos`.  WDYT?

**Comment by perezd** [comment]
So that does appear to work, but it feels awkward. I would press forward with this, but I will probably just wrap that in a macro def to reduce the noise at call sites.

Larger more strategic question: maybe we should consider making proto_descriptor_set_out a "proto language" rule? Its described as effectively an output target anyhow like java/cpp/etc.:
https://developers.google.com/protocol-buffers/docs/techniques#self-description

WDYT?

**Comment by pcj** [comment]
So what would that look like?  Something like:

```python
proto_language(
    name = "descriptor",
    args = [
         "--include_imports",
         "--include_source_info",
     ],
     pb_imports = ["external/com_github_google_protobuf/src"],
     pb_inputs = ["@com_github_google_protobuf//:well_known_protos"],
)

descriptor_proto_library(
  name = "api",
  protos = [...],
)
```

**Comment by perezd** [comment]
Yeah I think that makes the most sense. The output of that would be `api.pb.descriptor`. Although, I would still prefer "srcs" over "protos" :smile:

**Comment by pcj** [comment]
@perezd Merged this and created separate issue for descriptor language issue.

**Comment by perezd** [comment]
Awesome, thank you for this!

**Pull request merged**
