### PR TITLE
Update grpc to 1.9.1

### LINKED ISSUE #187: Upgrading gRpc to 1.9.1
Hello,

I'm trying to upgrade gprc to v1.9.1 by overriding dependencies.
I also added some dependencies in https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl (like protobuf_headers) manually since the current deps rule doesn't include them.

But I got the following error.

```
...
WARNING: /home/jhahn/.cache/bazel/_bazel_jhahn/096b9924a546d44702313d7a4b963776/external/com_google_grpc_base/WORKSPACE:1: Workspace name in /home/jhahn/.cache/bazel/_bazel_jhahn/096b9924a546d44702313d7a4b963776/external/com_google_grpc_base/WORKSPACE (@com_github_grpc_grpc) does not match the name given in the repository's definition (@com_google_grpc_base); this will cause a build error in future versions
ERROR: /home/jhahn/.cache/bazel/_bazel_jhahn/096b9924a546d44702313d7a4b963776/external/com_google_grpc/third_party/cares/BUILD:37:1: rule 'ares_build_h' has file 'ares_build.h' as both an input and an output
...
```

I guess this might be related to symlinks by grpc_repository(). Is this a known issue?

Thanks,

### PR DESCRIPTION
**Pull request by pcj**
- Remove grpc_repository.bzl.  This was previously used to eliminate
  grpc/grpc addiction to submodules and c-ares issues, which is
  now improved in source repo.
- Add grpc_archive.bzl.  We still need to patch the generate_cc.bzl
  file (should probably just upstream this change there).
- Remove previous references to @com_google_grpc.
- Update boringssl.

Fixes #187

### CODE REVIEW

**Comment by pcj** [comment]
@junghoahnsc I'd like to get travis green before merging this, but would bo good if you can test it.

**Comment by junghoahnsc** [comment]
@pcj cool! will try.

**Comment by promiseofcake** [comment]
The problem is that https://github.com/bazelbuild/rules_closure needs to either cut a release, or we can point to the current HEAD commit. https://github.com/bazelbuild/rules_closure/issues/254

**Comment by junghoahnsc** [comment]
I just verified in my local client and it seems to work.

**Comment by junghoahnsc** [comment]
@pcj are you going to submit this soon?
Thanks,

**Comment by promiseofcake** [comment]
@junghoahnsc, I think we need to update `rules_closure` to get Travis to Green. https://github.com/bazelbuild/rules_closure/issues/254, let's point to HEAD.

**Pull request closed without merging**
