### PR TITLE
Add python helloworld.Greeter server

### PR DESCRIPTION
**Pull request by drtechniko**
It can be run with
```
bazel run //examples/helloworld/python:greeter_server
```

but if one wants to run the client from bazel then it's best to run the server directly from ```bazel-bin```.

Also did a bit of clean up on the python client side.

### CODE REVIEW

**Comment by drtechniko** [comment]
@pcj let me know what you think.

**Comment by pcj** [comment]
Looks good!  Let me test it a bit, may not be able to to this until weekend.  Maybe we can add the results of the python server to https://github.com/pubref/grpc_greetertimer as well.

**Comment by drtechniko** [comment]
Sure, I can put a new PR when I get the chance for the timer service in a separate PR.

**Comment by pcj** [comment]
LGTM; a py_test integration test would also be welcome.  

Currently to test matrix excludes the python rules due to the pypi issue.  Once able to fetch the grpc python deps this will be particularly useful.

**Comment by drtechniko** [comment]
Sounds good. I'll submit on a separate PR.

**Pull request merged**
