### PR TITLE
automatically export //java:grpc_compiletime_deps when with_Grpc = true

### PR DESCRIPTION
**Pull request by perezd**
This makes it easier on users to not have to remember to import //java:grpc_compiletime_deps on their own.

### CODE REVIEW

**Comment by perezd** [comment]
This addresses #52.

**Comment by pcj** [comment]
The tests have been a little flaky lately, and travis queue seems to be getting longer and longer.  I restarted the job.

**Comment by pcj** [comment]
Can you: 

1. Document this behavior in the [README.md](https://github.com/pubref/rules_protobuf/blame/master/java/README.md#L54) for the java rules?

2. Comment out the `grpc_compiletime_deps` in the [client](https://github.com/pubref/rules_protobuf/blob/master/examples/helloworld/java/org/pubref/rules_protobuf/examples/helloworld/client/BUILD#L31) and [server](https://github.com/pubref/rules_protobuf/blob/master/examples/helloworld/java/org/pubref/rules_protobuf/examples/helloworld/server/BUILD#L32) helloworld example, leaving a comment that it is automatically exported by the proto rule?

**Comment by perezd** [comment]
OK, updated those items.

**Comment by perezd** [comment]
Oh shoot, forgot the comment in the build file...should I add that still?

**Comment by pcj** [comment]
Might be nice in case someone has a non-first order dependency that won't be satisfied by `export`, less digging to figure out the magic.

If you want to just `commit --amend` and `git push --force auto-export-grpc` won't make an extra commit.

**Comment by perezd** [comment]
OK all patched up.

**Comment by pcj** [comment]
LGTM

**Pull request merged**
