### PR TITLE
Sample for testing objc protocol dependencies.

### PR DESCRIPTION
**Pull request by spinorx**
Note that "@com_google_protobuf//:protobuf_objc" does not work anymore.  So needed to use "@com_google_protobuf//:objectivec"

### CODE REVIEW

**Comment by pcj** [comment]
I'm having trouble with `bazel build @com_google_protobuf//:objectivec`:

```sh
pcj@bina:~/github/pubref/rules_protobuf/tests/objc_proto_dep_test$ bazel build @com_google_protobuf//:objectivec
ERROR: /home/pcj/.cache/bazel/_bazel_pcj/cd482bd0a1c832391b6a145249b15e20/external/com_google_protobuf/BUILD:908:1: in objc_library rule @com_google_protobuf//:objectivec: Expected action_config for 'objc-compile' to be configured
ERROR: Analysis of target '@com_google_protobuf//:objectivec' failed; build aborted: Analysis of target '@com_google_protobuf//:objectivec' failed; build aborted
```

This is bazel 0.7.0 on linux.  Any ideas?  I also posted a question on bazel-discuss.  Updating com_google_protobuf to your recent commit to the root BUILD file did not resolve this error for me.

**Comment by spinorx** [comment]
Sorry, I was working on a mac.

Also I missed sending what my .bazelrc looks like.  That also might be part of equation.
in .bazelrc

build:ios --ios_multi_cpus=x86_64,armv7,arm64
build:ios --ios_sdk_version=11.0

tried with bazel build --config ios <target>

**Comment by pcj** [comment]
Hmm.  That didn't work either.  Based on a response on the mailing list, I don't think this will work on linux.  I'll try again tonight on my mac at home.  Recently switched to a linux-based laptop.

**Comment by codesuki** [comment]
I the same error. Using 0.8.1 or rules_protobuf and making an objc_protobuf_library rule.
```ERROR: /private/var/tmp/_bazel_a13575/ccc5d4b37b3e36132f6eea4b14c1e243/external/com_google_protobuf/BUILD:219:1: in objc_library rule @com_google_protobuf//:protobuf_objc: Expected action_config for 'objc-compile' to be configured
ERROR: Analysis of target '//proto/feature:feature_swift_proto' failed; build aborted: Analysis of target '@com_google_protobuf//:protobuf_objc' failed; build aborted```

Is there any way to fix this?

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues/PRs on this repo, apologies in advance for closing without proper response.

**Pull request closed without merging**
