### PR TITLE
Add pb_outputs to proto_language

### PR DESCRIPTION
**Pull request by jwahlin**
My team and I have been running into issues with proto_language() being too limited for the outputs our protoc command generates. Our protoc command generates multiple files, some of which should be in a new directory. One of those files should have a name that doesn't include the source proto's base name. The pb_file_extensions attribute limits what we can output with protoc. I would like to add a new pb_outputs attribute which allows more flexibility for the outputs. Here's an example of what pb_outputs would allow:
<pre>pb_outputs = [
    "persist_lib/pkg_level_definitions.persist.go",
    "persist_lib/*_queries.persist.go",
    "persist_lib/*_query_handlers.persist.go",
    "*.persist.go",
]</pre>
The * will be replaced, in Skylark, with the source proto's base name.

This PR works for our needs. Do these changes look suitable for master?

### CODE REVIEW

**Comment by pcj** [comment]
Is this output from a custom protoc plugin?  Or perhaps a plugin to the protoc-gen-go?  Or something else?  What does your current `proto_language` definition look like?

**Comment by pcj** [comment]
Also, if a replacement syntax is needed, I'd recommend the python/skylark format syntax, like:

```python
pb_outputs = [
    "persist_lib/pkg_level_definitions.persist.go",
    "persist_lib/{basename}_queries.persist.go",
    "persist_lib/{basename}_query_handlers.persist.go",
    "{basename}.persist.go",
]
```

And then do the replacement similar to https://github.com/pubref/rules_protobuf/blob/f20e112465643daa58f23199dbf163b7193640f9/protobuf/internal/github_archive.bzl#L7

This way a known/extensible set of tokens can be replaced.

**Comment by jwahlin** [comment]
Thanks for the information about the format() method. I committed that change just now. 

I'm using this protoc plugin:
https://github.com/tcncloud/protoc-gen-persist

Here's what my proto_language definition currently looks like:
<pre>proto_language(
    name = "persist_lib",
    pb_outputs = [
        "persist_lib/pkg_level_definitions.persist.go",
        "persist_lib/{basename}_queries.persist.go",
        "persist_lib/{basename}_query_handlers.persist.go",
    ],
    pb_options = ["persist_root=mybtest/lib"],
    pb_plugin = "@protoc_gen_persist//:protoc-gen-persist",
    supports_pb = True,
)</pre>

What are your thoughts?

**Comment by pcj** [comment]
Looks like an interesting plugin. Let me take a look...

**Comment by pcj** [comment]
Yeah I think this makes sense. Can we document it better at https://github.com/pubref/rules_protobuf/tree/master/protobuf#proto_language?

**Comment by jwahlin** [comment]
Definitely. I added some documentation just now. Is there anything you would recommend changing in that?

**Comment by pcj** [comment]
I put together a test example at `tests/protoc-gen-persist` that I need to tune up and will plan to add to your PR branch, but I probably won't be able to finish that until the weekend.

**Comment by jwahlin** [comment]
Sounds good. Thanks for the responsiveness.

**Comment by pcj** [comment]
The go_package option causes issues in bazel that is not working for `go_proto_library` definitions outside the root of the workspace.  I think in order to fully support protoc-gen-persist, this will need to be addressed (separate PR).  I think we can merge this and move on with that.

**Pull request merged**
