### PR TITLE
Add py_proto_library rule and use rules_python for pip requirements

### LINKED ISSUE #3: Python support requires pip or pypi
In order to support python fully in rules_protobuf, support for pulling dependencies from pip or pypi is required.  This is non-trivial for grpc as there is c-compilation involved with package installation.  Requires https://github.com/bazelbuild/bazel/issues/699 or similar.

### PR DESCRIPTION
**Pull request by pcj**
Fixes #3

### CODE REVIEW

**Comment by mattmoor** [comment]
@pcj any change you can rebase this after the `importpath` change to the go support? :D

**Comment by pcj** [comment]
@mattmoor Can you clarify your request?  Are you saying "rebase now" or "rebase following $(wait for some condition)"?  If you meant the latter, what is the condition?

**Comment by mattmoor** [comment]
Not a rush, but I was hoping you could rebase the PR now.  I'm building on your PR that builds on my PR :)

Basically, I am adding sample gRPC services in each languages that deploy to K8s in `bazelbuild/rules_k8s`.  For Python, I need your PR, which needs my PR.

However, I already have a Go sample (that consumes your `importpath` fix), which breaks because your PR doesn't have the `importpath` change.  For now, I just commented out the Go stuff, and I ran into [an issue](https://github.com/bazelbuild/rules_docker/issues/139) I need to resolve myself, so maybe I can stack the list of uncommitted changes even higher before I'm done....

thanks for all of this stuff, and the quick changes it's been very helpful 👍

**Comment by mattmoor** [comment]
@pcj To clarify I wasn't suggesting you should merge this as-is, just rebase your PR on master.  Something like:
```shell
# Update master
git checkout master
git pull origin master
# Rebase py
git checkout py
git rebase master
git push -f origin py
```

I just don't want to break you as I'm iterating on code review feedback.

**Comment by pcj** [comment]
OK, I think I see.  Well, looks like my master will be pointing to an intermediate commit before you renamed 'packages' to 'package', that should be OK for now.  

I pushed up a new/different PR #125 that rebases and points to your most recent feedback commit.  Hopefully we won't end up in some strange require loop.

**Comment by mattmoor** [comment]
Yeah they are all separate repos, so as long as we use pinned deps we should be fine.  Apologies if I was unclear.

Definitely CC me if issues crop up, and I'll do my best to TAL.

**Pull request merged**
